### ISSUE TITLE
[Bug]在开启pjax时切换页会导致"a"标签占满全屏

### ISSUE THREAD

**Issue by misaka10843** [Sanakey/KirinShiKi#10]
在开启pjax时切换页会导致当前页面最下面的链接“替换”全页
例如此视频：

https://user-images.githubusercontent.com/69132853/183286878-770cb034-02ec-4a3c-a839-ba02007b7b95.mp4

目前认为是css中的此段(在更小的屏幕下似乎并没此bug)
```css
@media screen and (min-width: 1200px)
#post-panel .ahover {
    display: block;
    position: absolute;
    top: 0;
    left: 0;
    right: 0;
    bottom: 0;
}
```
中的`bottom: 0;`问题，在刷新后问题解决

虽然可能只要修改css即可解决，但是怕修改后会出现其他问题就还是写了个issue问下

**Handsome主题为8.4.1**
